QUIZ 1

Nama: Muhamad Al Kausar Ramadhan

Absen: 15

Nim: 2041720193

TASK

1. Pastikan semua variabel kategorial diolah dengan baik. (Gunakan fitur mapping pada pandas)
2. Cek kondisi multicollinearity untuk semua variabel independen. Jika ada, antar variabel apakah itu?
3. Pastikan model menggunakan variabel yang tidak memiliki nilai multicollinearity yang tinggi
4. (Hints) Anda dapat menggunakan nilai Variance Inflation Factor (VIF) untuk mengetahui tingkat multicollinearity pada sebuah variabel independent.
5. Evaluasi model yang Anda buat dengan nilai R2
6.  Simpulkan, variabel independen apa saja yang dapat digunakan untuk menghasilkan model regresi yang baik pada kasus medical insurance costs?

In [58]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [59]:
df = pd.read_csv('data/insurance.csv')
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

TASK 1
1. Pastikan semua variabel kategorial diolah dengan baik. (Gunakan fitur mapping pada pandas)

JAWABAN
1. Pada kode dibawah ini digunakan untuk mengubah nilai kategorial menjadi angka

In [60]:
new_sex = {
    'male': 1,
    'female': 0
}

new_smoker ={
    'yes' : 1,
    'no' : 0
}

new_region ={
    'northwest' : 0,
    'southwest' : 1,
    'southeast' : 2,
    'northeast' : 3 
}

# Mengubah Isi Data dari column sex, smoker, region
df['sex'] = df['sex'].map(new_sex)
df['smoker'] = df['smoker'].map(new_smoker)
df['region'] = df['region'].map(new_region)


# Cek data
df.head()

   age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       1  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       0  21984.47061
4   32    1  28.880         0       0       0   3866.85520

In [61]:
new_df = df;
new_df.head()

   age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       1  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       0  21984.47061
4   32    1  28.880         0       0       0   3866.85520

TASK

2. Cek kondisi multicollinearity untuk semua variabel independen. Jika ada, antar variabel apakah itu?
3. Pastikan model menggunakan variabel yang tidak memiliki nilai multicollinearity yang tinggi
4. (Hints) Anda dapat menggunakan nilai Variance Inflation Factor (VIF) untuk mengetahui tingkat multicollinearity pada sebuah variabel independent.

JAWABAN

Proses kodingan dibawah merupakan proses untuk pengecekan kondisi dari multicollinearit. Berikut kondisi dari semua variable indapenden
1. Age = 7,5..
2. Sex = 2,0..
3. Bmi = 9,9..
4. Childern = 1,7..
5. Smoker = 1,2..
6. Region = 2,7..

dari hasil berikut terdapat ada 2 variable yang memiliki nilai yang tinggi yaitu Age, dan Bmi

In [62]:
# the independent variables set
data_set = new_df[['age', 'sex', 'bmi', 'children', 'smoker', 'region']]
  
# VIF dataframe
vif_data = pd.DataFrame()
vif_data["feature"] = data_set.columns
  
# calculating VIF for each feature
vif_data["VIF"] = [variance_inflation_factor(data_set.values, i)
                          for i in range(len(data_set.columns))]
  
print(vif_data)

    feature       VIF
0       age  7.588734
1       sex  2.002652
2       bmi  9.938670
3  children  1.799980
4    smoker  1.261195
5    region  2.789478

In [63]:
new_df = new_df.drop(df.columns[0], axis=1)
new_df = new_df.drop(df.columns[2], axis=1)
new_df.head()

   sex  children  smoker  region      charges
0    0         0       1       1  16884.92400
1    1         1       0       2   1725.55230
2    1         3       0       2   4449.46200
3    1         0       0       0  21984.47061
4    1         0       0       0   3866.85520

TASK
5. Evaluasi model yang Anda buat dengan nilai R2

JAWABAN
5. Proses dibawah merupakan proses prediksi untuk menemukan nilai r2_score

In [64]:
X = new_df.iloc[:, :-1].values
y = new_df.iloc[:, 4].values

In [65]:
y = y.reshape(len(y), 1)
y.shape

(1338, 1)

In [66]:
Xm_train, Xm_test, ym_train, ym_test = train_test_split(X, y, test_size=0.2, random_state=50)

In [67]:
mlr = LinearRegression()
mlr.fit(Xm_train, ym_train)

ym_pred = mlr.predict(Xm_test)

In [68]:
join = np.concatenate((ym_test, ym_pred), axis=1)
join

array([[ 5976.8311    ,  8259.47914707],
       [ 5846.9176    ,  8853.31976538],
       [13831.1152    ,  7803.35826235],
       [ 9625.92      ,  7622.16018086],
       [ 2680.9493    ,  7716.40156656],
       [47896.79135   , 31346.94065976],
       [18223.4512    , 32491.1435485 ],
       [ 7419.4779    ,  7578.68183297],
       [ 3732.6251    ,  7709.11687664],
       [12222.8983    ,  7578.68183297],
       [ 7050.0213    ,  7709.11687664],
       [21978.6769    , 31441.18204547],
       [ 6282.235     ,  8353.72053277],
       [37701.8768    , 31346.94065976],
       [ 7046.7222    ,  8259.47914707],
       [12032.326     ,  8216.00079918],
       [13112.6048    ,  8310.24218488],
       [ 4239.89265   ,  8310.24218488],
       [12333.828     ,  8353.72053277],
       [ 3410.324     ,  8216.00079918],
       [ 1727.785     ,  7622.16018086],
       [44641.1974    , 31940.78127808],
       [17128.42608   , 10222.1990835 ],
       [ 6112.35295   ,  8172.52245128],
       [ 4529.477     ,  8809.84141749],
       [10594.50155   ,  7716.40156656],
       [ 6402.29135   ,  8896.79811327],
       [46151.1245    , 32628.8632821 ],
       [ 1711.0268    ,  8397.19888066],
       [ 1704.70015   ,  7846.83661024],
       [45863.205     , 30709.62169355],
       [ 4687.797     , 10591.36327244],
       [15019.76005   ,  8766.3630696 ],
       [ 3180.5101    ,  8853.31976538],
       [ 3861.20965   ,  9628.35846519],
       [ 3443.064     ,  9541.4017694 ],
       [27117.99378   ,  7665.63852875],
       [ 2709.24395   ,  8172.52245128],
       [13451.122     ,  7622.16018086],
       [47928.03      , 31259.98396398],
       [23563.01618   ,  8991.03949898],
       [ 6710.1919    ,  8904.0828032 ],
       [14235.072     ,  8809.84141749],
       [14001.1338    ,  9447.1603837 ],
       [27218.43725   , 30890.81977504],
       [13390.559     ,  7759.87991446],
       [41034.2214    , 31484.66039336],
       [ 2020.177     ,  7622.16018086],
       [14256.1928    ,  7578.68183297],
       [21232.18226   ,  7759.87991446],
       [48675.5177    , 31441.18204547],
       [ 6986.697     ,  8904.0828032 ],
       [ 4149.736     ,  8216.00079918],
       [30942.1918    , 32491.1435485 ],
       [ 8023.13545   ,  8172.52245128],
       [42124.5153    , 32628.8632821 ],
       [11837.16      ,  7622.16018086],
       [ 6640.54485   ,  9034.51784687],
       [ 6666.243     , 10729.08300603],
       [10848.1343    ,  8766.3630696 ],
       [14394.39815   , 10084.47934991],
       [ 7201.70085   ,  8766.3630696 ],
       [ 1977.815     ,  7759.87991446],
       [ 1635.73365   ,  7716.40156656],
       [ 7256.7231    ,  8904.0828032 ],
       [ 8538.28845   ,  9490.63873159],
       [ 3857.75925   ,  7846.83661024],
       [ 9880.068     ,  8216.00079918],
       [ 4883.866     ,  7622.16018086],
       [21797.0004    ,  7759.87991446],
       [13880.949     ,  7622.16018086],
       [ 4779.6023    ,  8259.47914707],
       [ 3481.868     ,  9628.35846519],
       [ 5397.6167    ,  7665.63852875],
       [ 9583.8933    ,  8172.52245128],
       [17081.08      , 30666.14334566],
       [ 6600.361     ,  8947.56115109],
       [ 9715.841     ,  8896.79811327],
       [24393.6224    , 30760.38473137],
       [ 1631.8212    ,  7665.63852875],
       [ 2850.68375   ,  7578.68183297],
       [18246.4955    , 30847.34142715],
       [ 2457.502     ,  7622.16018086],
       [12928.7911    ,  8991.03949898],
       [ 1967.0227    ,  7846.83661024],
       [ 2643.2685    ,  8310.24218488],
       [11987.1682    ,  9584.88011729],
       [ 4877.98105   , 10091.76403983],
       [ 3046.062     ,  7709.11687664],
       [ 4544.2348    ,  7709.11687664],
       [ 3736.4647    ,  7578.68183297],
       [ 8596.8278    , 10634.84162033],
       [ 3756.6216    ,  7665.63852875],
       [36021.0112    , 31897.30293019],
       [24520.264     , 31259.98396398],
       [11305.93455   ,  8172.52245128],
       [ 7512.267     , 10135.24238772],
       [12094.478     ,  9403.68203581],
       [16297.846     , 30803.86307926],
       [23288.9284    ,  8302.95749496],
       [24671.66334   , 10084.47934991],
       [ 2201.0971    ,  8259.47914707],
       [43921.1837    , 30760.38473137],
       [14382.70905   ,  9360.20368791],
       [17179.522     , 31441.18204547],
       [ 8547.6913    ,  8259.47914707],
       [38709.176     , 31441.18204547],
       [ 9957.7216    ,  8440.67722856],
       [ 9910.35985   ,  8172.52245128],
       [ 5649.715     ,  7622.16018086],
       [ 5488.262     ,  8353.72053277],
       [ 8988.15875   ,  7578.68183297],
       [ 1826.843     ,  7759.87991446],
       [ 1837.2819    ,  7803.35826235],
       [ 1639.5631    ,  7716.40156656],
       [ 4934.705     ,  8809.84141749],
       [ 5425.02335   ,  9497.92342151],
       [28923.13692   ,  7578.68183297],
       [14210.53595   ,  7716.40156656],
       [24106.91255   , 32534.62189639],
       [ 1526.312     ,  7759.87991446],
       [ 5327.40025   ,  8766.3630696 ],
       [ 1136.3994    ,  7803.35826235],
       [ 1625.43375   ,  7716.40156656],
       [11881.9696    ,  8853.31976538],
       [ 4536.259     ,  8353.72053277],
       [ 7281.5056    ,  9360.20368791],
       [ 8835.26495   ,  7716.40156656],
       [ 8062.764     ,  8353.72053277],
       [ 3591.48      ,  9541.4017694 ],
       [48673.5588    , 30847.34142715],
       [11289.10925   ,  9497.92342151],
       [46200.9851    , 31897.30293019],
       [24227.33724   ,  7665.63852875],
       [20234.85475   , 30622.66499777],
       [24869.8368    , 32672.34162999],
       [20009.63365   , 31354.22534968],
       [ 6555.07035   ,  8302.95749496],
       [ 8277.523     ,  7622.16018086],
       [ 4571.41305   ,  7578.68183297],
       [12622.1795    ,  7578.68183297],
       [ 4185.0979    ,  7665.63852875],
       [ 5312.16985   ,  9360.20368791],
       [18804.7524    ,  9360.20368791],
       [ 6748.5912    ,  9628.35846519],
       [ 7162.0122    ,  8991.03949898],
       [ 5245.2269    ,  8259.47914707],
       [ 8515.7587    ,  8853.31976538],
       [ 6858.4796    ,  8440.67722856],
       [ 4349.462     ,  8853.31976538],
       [40974.1649    , 30709.62169355],
       [ 4433.9159    ,  8904.0828032 ],
       [ 1980.07      ,  8353.72053277],
       [51194.55914   , 31397.70369758],
       [ 2026.9741    ,  7665.63852875],
       [27346.04207   ,  7803.35826235],
       [13126.67745   ,  7622.16018086],
       [20462.99766   ,  9447.1603837 ],
       [20296.86345   , 31346.94065976],
       [12244.531     ,  7665.63852875],
       [ 7740.337     ,  8947.56115109],
       [ 9778.3472    ,  8302.95749496],
       [ 5584.3057    ,  8991.03949898],
       [10959.33      ,  7759.87991446],
       [ 2721.3208    ,  7846.83661024],
       [ 5003.853     ,  8216.00079918],
       [ 6796.86325   ,  9497.92342151],
       [ 1769.53165   ,  7716.40156656],
       [21348.706     , 30622.66499777],
       [ 1622.1885    ,  7665.63852875],
       [48885.13561   , 30709.62169355],
       [22493.65964   ,  8904.0828032 ],
       [12629.8967    ,  7665.63852875],
       [ 7337.748     ,  8216.00079918],
       [39983.42595   , 32404.18685272],
       [ 1391.5287    ,  7803.35826235],
       [41097.16175   , 30890.81977504],
       [ 7682.67      ,  9447.1603837 ],
       [37165.1638    , 31441.18204547],
       [ 9563.029     ,  9541.4017694 ],
       [10214.636     ,  7759.87991446],
       [12646.207     ,  8809.84141749],
       [ 5699.8375    ,  7803.35826235],
       [11013.7119    ,  8991.03949898],
       [19442.3535    ,  8904.0828032 ],
       [44423.803     , 30709.62169355],
       [42760.5022    , 31948.065968  ],
       [ 9301.89355   ,  9497.92342151],
       [39836.519     , 31853.82458229],
       [10156.7832    ,  8766.3630696 ],
       [ 4433.3877    ,  8904.0828032 ],
       [37742.5757    , 30847.34142715],
       [ 8782.469     ,  7759.87991446],
       [11512.405     ,  8302.95749496],
       [25517.11363   ,  8440.67722856],
       [10806.839     ,  8809.84141749],
       [39774.2763    , 31484.66039336],
       [ 5385.3379    ,  8172.52245128],
       [ 2128.43105   ,  7578.68183297],
       [37270.1512    , 30753.10004145],
       [33307.5508    , 30622.66499777],
       [12957.118     ,  7759.87991446],
       [ 7727.2532    ,  8172.52245128],
       [11856.4115    ,  7665.63852875],
       [ 5729.0053    ,  8904.0828032 ],
       [15820.699     , 30803.86307926],
       [ 9447.3824    ,  8302.95749496],
       [12638.195     ,  7622.16018086],
       [44260.7499    , 32035.02266378],
       [10977.2063    , 10041.00100201],
       [19107.7796    , 31303.46231187],
       [14988.432     ,  8947.56115109],
       [ 9630.397     ,  8947.56115109],
       [47269.854     , 32035.02266378],
       [13063.883     ,  7622.16018086],
       [ 1824.2854    ,  7803.35826235],
       [11763.0009    ,  8440.67722856],
       [ 9861.025     ,  8216.00079918],
       [36950.2567    , 30847.34142715],
       [ 2103.08      ,  8353.72053277],
       [ 2198.18985   ,  7709.11687664],
       [38415.474     , 31991.54431589],
       [ 8627.5411    ,  8440.67722856],
       [ 4237.12655   ,  8440.67722856],
       [ 4441.21315   ,  8440.67722856],
       [ 9872.701     ,  8216.00079918],
       [32108.66282   ,  9034.51784687],
       [20878.78443   ,  7709.11687664],
       [ 2699.56835   ,  7716.40156656],
       [ 7731.85785   ,  7578.68183297],
       [21082.16      , 31397.70369758],
       [ 2730.10785   ,  8172.52245128],
       [11326.71487   ,  8397.19888066],
       [ 3925.7582    ,  8896.79811327],
       [38282.7495    , 31441.18204547],
       [12235.8392    ,  7578.68183297],
       [10115.00885   ,  9360.20368791],
       [ 8932.084     ,  7622.16018086],
       [14001.2867    ,  9447.1603837 ],
       [35595.5898    , 32491.1435485 ],
       [15230.32405   ,  8896.79811327],
       [ 6059.173     , 10135.24238772],
       [ 2166.732     ,  7622.16018086],
       [ 8944.1151    ,  9584.88011729],
       [ 4058.1161    ,  8991.03949898],
       [12323.936     ,  7846.83661024],
       [33732.6867    , 30890.81977504],
       [ 5375.038     ,  8809.84141749],
       [ 1972.95      ,  7759.87991446],
       [10704.47      ,  7622.16018086],
       [11842.62375   ,  7578.68183297],
       [ 3866.8552    ,  7716.40156656],
       [ 6128.79745   ,  9360.20368791],
       [11070.535     ,  7622.16018086],
       [10560.4917    ,  9584.88011729],
       [11938.25595   ,  7846.83661024],
       [12741.16745   ,  7846.83661024],
       [11729.6795    ,  8896.79811327],
       [ 2362.22905   ,  8310.24218488],
       [ 9500.57305   ,  9628.35846519],
       [ 6184.2994    ,  9447.1603837 ],
       [13887.9685    ,  7665.63852875],
       [13224.693     ,  8216.00079918],
       [ 3392.3652    ,  8259.47914707],
       [ 4931.647     ,  8809.84141749],
       [ 9724.53      ,  8353.72053277],
       [36580.28216   , 10041.00100201],
       [37133.8982    , 30709.62169355]])

In [69]:
r2_mlr = r2_score(ym_test, ym_pred)
print(r2_mlr)

0.6559958079837158

TASK

6. Simpulkan, variabel independen apa saja yang dapat digunakan untuk menghasilkan model regresi yang baik pada kasus medical insurance costs?

In [70]:
X6 = df.iloc[:, :-1].values
y6 = df.iloc[:, 6].values

In [71]:
y6 = y6.reshape(len(y), 1)
y6.shape

(1338, 1)

In [76]:
Xm_train6, Xm_test6, ym_train6, ym_test6 = train_test_split(X6, y6, test_size=0.2, random_state=50)

In [77]:
mlr6 = LinearRegression()
mlr6.fit(Xm_train6, ym_train6)

ym_pred6 = mlr6.predict(Xm_test6)

In [78]:
gabung6 = np.concatenate((ym_test6, ym_pred6), axis=1)
gabung6

array([[ 5.97683110e+03,  8.02669491e+03],
       [ 5.84691760e+03,  1.16938407e+04],
       [ 1.38311152e+04,  1.71786170e+04],
       [ 9.62592000e+03,  1.13687219e+04],
       [ 2.68094930e+03,  4.67609884e+02],
       [ 4.78967913e+04,  3.87045302e+04],
       [ 1.82234512e+04,  2.62413412e+04],
       [ 7.41947790e+03,  7.89114229e+03],
       [ 3.73262510e+03,  7.64340489e+02],
       [ 1.22228983e+04,  1.16795655e+04],
       [ 7.05002130e+03,  9.23505349e+03],
       [ 2.19786769e+04,  3.20389021e+04],
       [ 6.28223500e+03,  8.15323277e+03],
       [ 3.77018768e+04,  3.08375213e+04],
       [ 7.04672220e+03,  7.61558919e+03],
       [ 1.20323260e+04,  9.55980129e+03],
       [ 1.31126048e+04,  1.16167569e+04],
       [ 4.23989265e+03,  4.77694453e+03],
       [ 1.23338280e+04,  1.23046130e+04],
       [ 3.41032400e+03,  8.74838942e+03],
       [ 1.72778500e+03, -1.22879102e+03],
       [ 4.46411974e+04,  3.65374536e+04],
       [ 1.71284261e+04,  6.53621123e+03],
       [ 6.11235295e+03,  8.97898395e+03],
       [ 4.52947700e+03,  4.31574332e+03],
       [ 1.05945016e+04,  1.09692130e+04],
       [ 6.40229135e+03,  5.35105861e+03],
       [ 4.61511245e+04,  3.79991539e+04],
       [ 1.71102680e+03,  5.29104947e+02],
       [ 1.70470015e+03, -3.93428374e+01],
       [ 4.58632050e+04,  3.72628449e+04],
       [ 4.68779700e+03,  4.33743188e+03],
       [ 1.50197601e+04,  1.46054920e+04],
       [ 3.18051010e+03,  1.36853647e+03],
       [ 3.86120965e+03,  1.11298477e+03],
       [ 3.44306400e+03,  6.09495004e+03],
       [ 2.71179938e+04,  9.30224165e+03],
       [ 2.70924395e+03,  1.41540873e+03],
       [ 1.34511220e+04,  1.19443733e+04],
       [ 4.79280300e+04,  3.91617990e+04],
       [ 2.35630162e+04,  9.68824527e+03],
       [ 6.71019190e+03,  6.78513321e+03],
       [ 1.42350720e+04,  1.70073442e+04],
       [ 1.40011338e+04,  1.32724110e+04],
       [ 2.72184372e+04,  3.52055455e+04],
       [ 1.33905590e+04,  1.39302242e+04],
       [ 4.10342214e+04,  3.39789701e+04],
       [ 2.02017700e+03,  4.58596872e+03],
       [ 1.42561928e+04,  1.26466707e+04],
       [ 2.12321823e+04,  9.74933525e+03],
       [ 4.86755177e+04,  3.98559896e+04],
       [ 6.98669700e+03,  9.49978725e+03],
       [ 4.14973600e+03,  6.60275122e+03],
       [ 3.09421918e+04,  3.79738009e+04],
       [ 8.02313545e+03,  1.16535772e+04],
       [ 4.21245153e+04,  3.52230801e+04],
       [ 1.18371600e+04,  1.09937604e+04],
       [ 6.64054485e+03,  3.91030773e+03],
       [ 6.66624300e+03,  1.21456900e+04],
       [ 1.08481343e+04,  1.37684916e+04],
       [ 1.43943982e+04,  1.34694008e+04],
       [ 7.20170085e+03,  7.45548672e+03],
       [ 1.97781500e+03,  3.57174222e+03],
       [ 1.63573365e+03,  1.90502761e+03],
       [ 7.25672310e+03,  9.21297345e+03],
       [ 8.53828845e+03,  1.03640638e+04],
       [ 3.85775925e+03,  5.71671612e+03],
       [ 9.88006800e+03,  1.41684121e+04],
       [ 4.88386600e+03,  5.73379540e+03],
       [ 2.17970004e+04,  1.50016528e+04],
       [ 1.38809490e+04,  1.43462428e+04],
       [ 4.77960230e+03,  5.99485843e+03],
       [ 3.48186800e+03,  3.56420413e+03],
       [ 5.39761670e+03,  9.82013498e+03],
       [ 9.58389330e+03,  1.22304916e+04],
       [ 1.70810800e+04,  2.55880331e+04],
       [ 6.60036100e+03,  8.67812632e+03],
       [ 9.71584100e+03,  9.38294791e+03],
       [ 2.43936224e+04,  3.36182301e+04],
       [ 1.63182120e+03,  4.92489598e+03],
       [ 2.85068375e+03,  3.93267720e+03],
       [ 1.82464955e+04,  2.77207188e+04],
       [ 2.45750200e+03,  1.55499215e+03],
       [ 1.29287911e+04,  1.40274229e+04],
       [ 1.96702270e+03,  1.99830658e+03],
       [ 2.64326850e+03,  4.20672752e+03],
       [ 1.19871682e+04,  1.41047497e+04],
       [ 4.87798105e+03,  4.78877623e+03],
       [ 3.04606200e+03,  2.69197734e+03],
       [ 4.54423480e+03,  2.79864120e+03],
       [ 3.73646470e+03,  3.96932743e+03],
       [ 8.59682780e+03,  1.11502443e+04],
       [ 3.75662160e+03,  4.25781375e+03],
       [ 3.60210112e+04,  2.88154796e+04],
       [ 2.45202640e+04,  3.36546406e+04],
       [ 1.13059345e+04,  1.12466428e+04],
       [ 7.51226700e+03,  9.19150387e+03],
       [ 1.20944780e+04,  1.05772988e+04],
       [ 1.62978460e+04,  2.52983921e+04],
       [ 2.32889284e+04,  3.41623227e+03],
       [ 2.46716633e+04,  5.88257017e+03],
       [ 2.20109710e+03,  8.72456429e+02],
       [ 4.39211837e+04,  3.66130005e+04],
       [ 1.43827090e+04,  1.30753592e+04],
       [ 1.71795220e+04,  2.84923035e+04],
       [ 8.54769130e+03,  9.89070254e+03],
       [ 3.87091760e+04,  3.23440392e+04],
       [ 9.95772160e+03,  1.02260455e+04],
       [ 9.91035985e+03,  1.10132228e+04],
       [ 5.64971500e+03,  8.57937692e+03],
       [ 5.48826200e+03,  8.08795831e+03],
       [ 8.98815875e+03,  1.02689374e+04],
       [ 1.82684300e+03,  4.92960613e+03],
       [ 1.83728190e+03,  7.23895007e+03],
       [ 1.63956310e+03,  2.77545328e+03],
       [ 4.93470500e+03,  5.20177692e+03],
       [ 5.42502335e+03,  7.25934832e+03],
       [ 2.89231369e+04,  1.17662608e+04],
       [ 1.42105359e+04,  1.64918520e+04],
       [ 2.41069126e+04,  3.29496410e+04],
       [ 1.52631200e+03,  3.38009016e+03],
       [ 5.32740025e+03,  7.46888157e+03],
       [ 1.13639940e+03,  3.36516016e+03],
       [ 1.62543375e+03, -4.36117309e+02],
       [ 1.18819696e+04,  1.25923883e+04],
       [ 4.53625900e+03,  1.08338901e+04],
       [ 7.28150560e+03,  7.82961165e+03],
       [ 8.83526495e+03,  1.11426655e+04],
       [ 8.06276400e+03,  1.07797392e+04],
       [ 3.59148000e+03,  5.68491809e+03],
       [ 4.86735588e+04,  3.98032430e+04],
       [ 1.12891092e+04,  1.31220711e+04],
       [ 4.62009851e+04,  3.76480758e+04],
       [ 2.42273372e+04,  1.62097890e+04],
       [ 2.02348547e+04,  2.96197505e+04],
       [ 2.48698368e+04,  3.37599910e+04],
       [ 2.00096336e+04,  2.96370016e+04],
       [ 6.55507035e+03,  6.88119140e+03],
       [ 8.27752300e+03,  9.62824908e+03],
       [ 4.57141305e+03,  5.19323182e+03],
       [ 1.26221795e+04,  1.32536617e+04],
       [ 4.18509790e+03,  4.31291467e+03],
       [ 5.31216985e+03,  5.09833779e+03],
       [ 1.88047524e+04,  6.13551855e+03],
       [ 6.74859120e+03,  7.64607665e+03],
       [ 7.16201220e+03,  1.14217040e+04],
       [ 5.24522690e+03,  8.37846651e+03],
       [ 8.51575870e+03,  9.32805357e+03],
       [ 6.85847960e+03,  6.49095427e+03],
       [ 4.34946200e+03,  6.65282700e+03],
       [ 4.09741649e+04,  3.43943902e+04],
       [ 4.43391590e+03,  6.65180339e+03],
       [ 1.98007000e+03,  4.15773890e+03],
       [ 5.11945591e+04,  3.07589640e+04],
       [ 2.02697410e+03,  6.06753943e+03],
       [ 2.73460421e+04,  1.15060939e+04],
       [ 1.31266774e+04,  3.00763925e+03],
       [ 2.04629977e+04,  1.50185694e+04],
       [ 2.02968635e+04,  2.95868891e+04],
       [ 1.22445310e+04,  1.43432553e+04],
       [ 7.74033700e+03,  1.19667246e+04],
       [ 9.77834720e+03,  1.07796890e+04],
       [ 5.58430570e+03,  9.03215556e+03],
       [ 1.09593300e+04,  1.01663194e+04],
       [ 2.72132080e+03,  2.72529442e+03],
       [ 5.00385300e+03,  6.06842734e+03],
       [ 6.79686325e+03,  8.72002142e+03],
       [ 1.76953165e+03,  2.75877159e+03],
       [ 2.13487060e+04,  3.09436831e+04],
       [ 1.62218850e+03,  2.73540417e+03],
       [ 4.88851356e+04,  3.49445113e+04],
       [ 2.24936596e+04,  2.58655069e+03],
       [ 1.26298967e+04,  1.12255834e+04],
       [ 7.33774800e+03,  9.10774659e+03],
       [ 3.99834259e+04,  3.28331066e+04],
       [ 1.39152870e+03,  3.76779947e+03],
       [ 4.10971617e+04,  3.43318330e+04],
       [ 7.68267000e+03,  1.01250375e+04],
       [ 3.71651638e+04,  2.95603179e+04],
       [ 9.56302900e+03,  1.25266887e+04],
       [ 1.02146360e+04,  1.16182713e+04],
       [ 1.26462070e+04,  1.56460042e+04],
       [ 5.69983750e+03,  9.15976575e+03],
       [ 1.10137119e+04,  9.35429467e+03],
       [ 1.94423535e+04,  7.04199421e+03],
       [ 4.44238030e+04,  3.68288660e+04],
       [ 4.27605022e+04,  3.55870975e+04],
       [ 9.30189355e+03,  9.38028248e+03],
       [ 3.98365190e+04,  3.30653875e+04],
       [ 1.01567832e+04,  8.99950643e+03],
       [ 4.43338770e+03,  6.53174468e+03],
       [ 3.77425757e+04,  3.16699567e+04],
       [ 8.78246900e+03,  9.18272175e+03],
       [ 1.15124050e+04,  1.25271759e+04],
       [ 2.55171136e+04,  1.02660445e+04],
       [ 1.08068390e+04,  1.28938154e+04],
       [ 3.97742763e+04,  3.24916310e+04],
       [ 5.38533790e+03,  5.78744377e+03],
       [ 2.12843105e+03,  2.84551322e+03],
       [ 3.72701512e+04,  3.08068908e+04],
       [ 3.33075508e+04,  2.61948521e+04],
       [ 1.29571180e+04,  1.07069003e+04],
       [ 7.72725320e+03,  1.06497598e+04],
       [ 1.18564115e+04,  1.53061892e+04],
       [ 5.72900530e+03,  9.01291684e+03],
       [ 1.58206990e+04,  2.74600204e+04],
       [ 9.44738240e+03,  9.44571018e+03],
       [ 1.26381950e+04,  1.31751644e+04],
       [ 4.42607499e+04,  3.70241676e+04],
       [ 1.09772063e+04,  1.55129423e+04],
       [ 1.91077796e+04,  2.83762076e+04],
       [ 1.49884320e+04,  1.34023770e+04],
       [ 9.63039700e+03,  1.19708960e+04],
       [ 4.72698540e+04,  3.89152816e+04],
       [ 1.30638830e+04,  1.76938586e+04],
       [ 1.82428540e+03,  4.28487383e+03],
       [ 1.17630009e+04,  1.28739728e+04],
       [ 9.86102500e+03,  9.83997953e+03],
       [ 3.69502567e+04,  3.04967926e+04],
       [ 2.10308000e+03,  1.03058868e+03],
       [ 2.19818985e+03,  1.08123084e+03],
       [ 3.84154740e+04,  3.22695409e+04],
       [ 8.62754110e+03,  6.51092281e+03],
       [ 4.23712655e+03,  4.87357222e+03],
       [ 4.44121315e+03,  4.88690520e+03],
       [ 9.87270100e+03,  1.24939090e+04],
       [ 3.21086628e+04,  9.51300646e+03],
       [ 2.08787844e+04,  1.06523789e+04],
       [ 2.69956835e+03,  4.69967954e+03],
       [ 7.73185785e+03,  1.11160459e+04],
       [ 2.10821600e+04,  3.09877723e+04],
       [ 2.73010785e+03,  6.15772793e+03],
       [ 1.13267149e+04,  1.03780289e+04],
       [ 3.92575820e+03,  5.56792066e+03],
       [ 3.82827495e+04,  3.17574571e+04],
       [ 1.22358392e+04,  1.46210039e+04],
       [ 1.01150089e+04,  1.23150698e+04],
       [ 8.93208400e+03,  9.09253475e+03],
       [ 1.40012867e+04,  1.33071649e+04],
       [ 3.55955898e+04,  2.84367733e+04],
       [ 1.52303240e+04,  1.68164802e+04],
       [ 6.05917300e+03,  7.60761261e+03],
       [ 2.16673200e+03,  5.28174071e+03],
       [ 8.94411510e+03,  1.49862953e+04],
       [ 4.05811610e+03,  8.16160248e+03],
       [ 1.23239360e+04,  1.08623735e+04],
       [ 3.37326867e+04,  2.61914052e+04],
       [ 5.37503800e+03,  7.95188002e+03],
       [ 1.97295000e+03,  2.46593828e+03],
       [ 1.07044700e+04,  1.19079123e+04],
       [ 1.18426238e+04,  1.28968343e+04],
       [ 3.86685520e+03,  5.53004440e+03],
       [ 6.12879745e+03,  8.27319627e+03],
       [ 1.10705350e+04,  1.05184540e+04],
       [ 1.05604917e+04,  1.29171789e+04],
       [ 1.19382560e+04,  1.23797891e+04],
       [ 1.27411675e+04,  1.49877174e+04],
       [ 1.17296795e+04,  1.00032100e+04],
       [ 2.36222905e+03,  4.02998816e+03],
       [ 9.50057305e+03,  8.88994958e+03],
       [ 6.18429940e+03,  7.42270453e+03],
       [ 1.38879685e+04,  1.58783645e+04],
       [ 1.32246930e+04,  1.30372708e+04],
       [ 3.39236520e+03,  4.60299778e+03],
       [ 4.93164700e+03,  4.50670015e+03],
       [ 9.72453000e+03,  1.13835089e+04],
       [ 3.65802822e+04,  1.59825632e+04],
       [ 3.71338982e+04,  3.00102852e+04]])

In [79]:
r2_mlr6 = r2_score(ym_test6, ym_pred6)
print(r2_mlr6)

0.7835627749480738

KESIMPULANYA ADALAH JIKA COLUMN YANG DIGUNAKAN HANYALAH NILAI VIF YANG KURANG DARI 5, MAKA HASILNYA TIDAK SEBAGUS DENGAN NILAI PREDIKSI YANG MENGGABUNGKAN SEMUA COLUMN